import { Link } from "wouter";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  ChevronRight,
  ArrowRight,
  TrendingUp,
  Lightbulb,
  Target,
  BarChart3,
} from "lucide-react";

export default function AdvancedStrategies() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-4xl mx-auto px-4 md:px-6 lg:px-8 py-8">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-sm text-muted-foreground mb-6">
          <Link
            href="/blog"
            className="hover:text-foreground transition-colors"
          >
            Blog
          </Link>
          <ChevronRight className="h-4 w-4" />
          <span className="text-foreground">The Search for Alpha</span>
        </nav>

        {/* Header */}
        <header className="mb-10">
          <div className="flex items-center gap-2 text-xs text-muted-foreground mb-3">
            <span className="bg-accent px-2 py-0.5 rounded">Strategy</span>
            <span>January 15, 2025</span>
            <span>•</span>
            <span>8 min read</span>
          </div>
          <h1 className="text-3xl font-bold mb-3">The Search for Alpha</h1>
        </header>

        {/* Top Disclaimer */}
        <Card className="p-3 bg-amber-500/10 border-l-4 border-l-amber-500 mb-6">
          <p className="text-xs text-muted-foreground italic">
            This content is for educational and research purposes only. Tiphub.ai does not provide buy/sell recommendations. Users must conduct independent analysis and consult qualified professionals before any trading decisions.
          </p>
        </Card>

        {/* Content */}
        <article className="prose prose-neutral dark:prose-invert max-w-none">
          {/* Section 1: The Search for Alpha */}
          <section className="mb-12">
            <p className="text-muted-foreground leading-relaxed mb-4">
              As a trader, investor, market researcher or a general enthusiast,
              alpha and beta are some terms you might have heard thrown around
              frequently when it comes to the stock market. Now what do these
              terms <em>mean</em> actually?
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              <strong>Beta</strong> for a portfolio is the correlation of the
              performance of a portfolio with respect to a benchmark. For
              example, if your portfolio returns are highly correlated to NIFTY,
              then you will have a beta close to 1. Since an index broadly
              captures the market sentiment in a particular exchange, beta is
              generally used as a reference metric for the expectation of the
              portfolio performance; given some forecast of the index
              performance. Simply put, if the broad sentiment is that the
              markets will perform well (say 20%, over the next quarter), then
              one can expect their portfolio (with a beta of 0.8) performance to
              be ~16%.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong>Alpha</strong> is the excess returns generated by a
              portfolio over the benchmark. Now that benchmark may be NIFTY, NQ,
              or even treasury bonds. The reason this is important is simply:
              The capital any investor has is limited, and is mostly cycled
              between different instruments. The reason any investor would
              prefer investment in a risky instrument is if it would generate
              significantly more returns than the same investment in a risk-free
              instrument. As a trader/investor, our entire goal boils down to
              the search for this mythical alpha. The question is, How?
            </p>
          </section>

          {/* Section 2: Institutions vs Retail */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">
              Institutions vs Retail: The Age Old Rivalry
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The two major participants in any market are the institutions like
              proprietary desks, funds, banks (also known as managed money/smart
              money, in retail lingo) and retail. Unlike how it is thought of,
              there is no hard line between them: you can have retail
              participants with large funds, and institutions with small ticket
              sizes.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              The real difference comes in the approach towards allocating the
              money. Institutions, by and large, have a specific pattern of
              allocating funds, whereas retail flow is generally random.
              Institutions also generally take a quantitative approach towards
              allocating the capital, whereas retail, by and large, takes
              positions guided by sentiment and emotions.
            </p>
          </section>

          {/* Section 3: Tiphub Platform */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
              <Target className="h-6 w-6 text-primary" />
              Tiphub: Democratizing Market Research
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Retail trading has never had a shortage of indicators—RSI, MACD,
              Bollinger Bands, Supertrend, you name it. The real bottleneck is{" "}
              <em>
                turning indicator intuition into a coherent, testable strategy
              </em>
              , and doing it in a way that avoids endless manual tinkering.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              That's exactly what Tiphub is built for: you choose the instrument
              (script), choose the indicators you trust, and our generative AI
              framework designs <strong>symbolic alpha expressions</strong>{" "}
              (i.e., interpretable trading signals), <strong>backtests</strong>{" "}
              them on historical data, and then{" "}
              <strong>selects the best-performing candidates</strong>—with the
              option to export the final logic as <strong>Pine Script</strong>{" "}
              for TradingView.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-4">
              The Tiphub workflow is exactly how quants in Wall Street funds
              generate alpha for their firms; it is built by a team of cracked
              researchers and traders with solid experience of working in
              high-frequency trading firms and top investment banks, with one
              goal: bringing institutional grade trading and research tools to
              general public, making markets fair for all.
            </p>

            <Card className="p-4 bg-muted/50 border-l-4 border-l-primary my-6">
              <p className="text-sm text-muted-foreground mb-2">
                Most "AI trading" products either:
              </p>
              <ul className="text-sm text-muted-foreground space-y-1 ml-4">
                <li>• Give you a black-box signal you can't validate, or</li>
                <li>
                  • Spit out code that's technically complex but conceptually
                  messy
                </li>
              </ul>
              <p className="text-sm text-muted-foreground mt-2">
                Our system takes the alternate route: it generates{" "}
                <strong>symbolic alpha expressions</strong>—compact,
                human-readable mathematical/logical formulas that combine your
                selected indicators into a trading signal.
              </p>
            </Card>

            <p className="text-muted-foreground leading-relaxed">
              Think of expressions like:
            </p>
            <ul className="text-muted-foreground space-y-2 my-4 ml-4">
              <li>
                • "Momentum is improving <em>and</em> volatility is compressing"
              </li>
              <li>
                • "Trend strength is high, but only take entries when price
                mean-reverts to a moving average"
              </li>
              <li>
                • "Buy when short-term strength flips upward while longer-term
                trend stays intact"
              </li>
            </ul>
            <p className="text-muted-foreground leading-relaxed">
              Even when the math is more formal under the hood, the output is
              designed to be <strong>interpretable</strong>,{" "}
              <strong>auditable</strong>, and <strong>exportable</strong>.
            </p>
          </section>

          {/* Section 4: The Core Workflow */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-6 flex items-center gap-2">
              <BarChart3 className="h-6 w-6 text-primary" />
              The Core Workflow
            </h2>

            {/* Step 1 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                1. Select Your Script (Instrument)
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                Start by choosing the asset you want to research—e.g., NIFTY
                stocks, BANKNIFTY constituents, crypto pairs, US equities, etc.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                This matters because "good alpha" is contextual:
              </p>
              <ul className="text-muted-foreground space-y-1 my-3 ml-4">
                <li>
                  • A mean-reversion idea might shine in a range-bound large-cap
                </li>
                <li>
                  • A trend-following idea might dominate in momentum-driven
                  assets
                </li>
              </ul>
            </div>

            {/* Step 2 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                2. Pick a Set of Technical Indicators
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                Next you choose the building blocks—your indicator toolkit. A
                simple way to think about it: try to cover{" "}
                <strong>different market "dimensions"</strong>:
              </p>
              <ul className="text-muted-foreground space-y-1 my-3 ml-4">
                <li>
                  • <strong>Trend:</strong> Moving averages, Supertrend, ADX
                </li>
                <li>
                  • <strong>Momentum:</strong> RSI, MACD, ROC
                </li>
                <li>
                  • <strong>Volatility:</strong> Bollinger Bands, ATR
                </li>
                <li>
                  • <strong>Volume (if available):</strong> OBV, volume MA, MFI
                </li>
              </ul>
              <Card className="p-4 bg-amber-500/10 border-l-4 border-l-amber-500 my-4">
                <p className="text-sm text-muted-foreground flex items-start gap-2">
                  <Lightbulb className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
                  <span>
                    <strong>Retail tip:</strong> Avoid selecting 12 indicators
                    "just because." More isn't always better; it expands the
                    search space and can create complex signals that don't
                    generalize, and overfit the data.
                  </span>
                </p>
              </Card>
            </div>

            {/* Step 3 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                3. Generate Symbolic Alphas
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                This is where the generative AI engine goes to work. It creates{" "}
                <em>multiple candidate alpha expressions</em> by combining your
                chosen indicators using transformations and logical
                structure—examples include:
              </p>
              <ul className="text-muted-foreground space-y-1 my-3 ml-4">
                <li>• Thresholds (e.g., RSI &lt; 30)</li>
                <li>• Crossovers (fast MA crosses above slow MA)</li>
                <li>• Normalization and scaling</li>
                <li>• Regime filters (e.g., only trade when ADX &gt; X)</li>
                <li>• Confirmation logic (A and B, or A but not B)</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed">
                Instead of you manually trying 50 variations, the system
                explores many <em>programmatically</em>.
              </p>
            </div>

            {/* Step 4 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                4. Backtesting on Historical Data
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                Each generated alpha is then backtested on your selected
                script's historical data. A robust backtest typically evaluates
                things like:
              </p>
              <ul className="text-muted-foreground space-y-1 my-3 ml-4">
                <li>• Overall returns</li>
                <li>• Win rate</li>
                <li>• Average win / average loss</li>
                <li>• Drawdown characteristics</li>
                <li>
                  • Stability across time (consistency matters more than one
                  lucky spike)
                </li>
              </ul>
              <Card className="p-4 bg-muted/50 border-l-4 border-l-primary my-4">
                <p className="text-sm text-muted-foreground">
                  <strong>Important note (analyst lens):</strong> The goal isn't
                  "highest return at any cost." The best alphas usually balance
                  performance with <em>risk control and consistency</em>.
                </p>
              </Card>
            </div>

            {/* Step 5 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                5. "Best Alpha" Selection: Ranked Outputs, Not Guesswork
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                After testing, the system ranks and shortlists the
                top-performing alphas, and provides the best performing
                expression.
              </p>
              <Card className="p-4 bg-amber-500/10 border-l-4 border-l-amber-500 my-4">
                <p className="text-sm text-muted-foreground flex items-start gap-2">
                  <Lightbulb className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
                  <span>
                    <strong>Key tip:</strong> Ideally you don't just get one
                    answer—you get <strong>a set of strong candidates</strong>{" "}
                    (every time you run the optimizer), which is closer to how
                    professional research works. As a researcher, you compare
                    alternatives, understand tradeoffs and select based on your
                    risk tolerance and trading style.
                  </span>
                </p>
              </Card>
            </div>

            {/* Step 6 */}
            <div className="mb-8">
              <h3 className="text-xl font-medium mb-3">
                6. Export to Pine Script for TradingView
              </h3>
              <p className="text-muted-foreground leading-relaxed mb-3">
                Once you've identified an alpha you like, you can extract{" "}
                <strong>Pine Script code</strong> for it. That means you can:
              </p>
              <ul className="text-muted-foreground space-y-1 my-3 ml-4">
                <li>• Plot signals directly on a TradingView chart</li>
                <li>
                  • Run TradingView's strategy tester (if exported as a
                  strategy)
                </li>
                <li>• Set alerts</li>
                <li>• Paper trade, forward test, and iterate</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed">
                This is the bridge from "research idea" → "execution
                environment."
              </p>
            </div>
          </section>

          {/* Section 5: How to Evaluate */}
          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">
              How to Evaluate "Best Performing" Like an Analyst (Not a Gambler)
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              When your shortlist comes back, here are the professional-grade
              checks that matter:
            </p>
            <ul className="text-muted-foreground space-y-3 my-4 ml-4">
              <li>
                <strong>Drawdown vs return:</strong> A slightly lower return
                with much lower drawdown is often the <em>better</em> strategy.
              </li>
              <li>
                <strong>Consistency:</strong> Prefer alphas that perform across
                multiple market regimes, not just one section of the chart.
              </li>
              <li>
                <strong>Simplicity:</strong> If two alphas perform similarly,
                the simpler symbolic expression usually generalizes better.
              </li>
              <li>
                <strong>Signal frequency:</strong> Too many trades can get eaten
                by costs/slippage; too few trades may be fragile.
              </li>
              <li>
                <strong>Forward testing:</strong> Export to Pine Script and
                paper trade / replay test before committing real capital.
              </li>
            </ul>
          </section>
        </article>

        {/* Bottom Disclaimer */}
        <Card className="p-3 bg-amber-500/10 border-l-4 border-l-amber-500 mt-8">
          <p className="text-xs text-muted-foreground italic">
            This content is for educational and research purposes only. Tiphub.ai does not provide buy/sell recommendations. Users must conduct independent analysis and consult qualified professionals before any trading decisions.
          </p>
        </Card>

        {/* CTA Card */}
        <Card className="p-6 mt-12 bg-gradient-to-r from-primary/10 to-primary/5 border-primary/20">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div>
              <h3 className="text-xl font-semibold mb-1">
                Ready to Generate Alpha?
              </h3>
              <p className="text-muted-foreground">
                Put these strategies into practice with our alpha generation
                engine.
              </p>
            </div>
            <Link href="/alpha-generation">
              <Button size="lg" className="gap-2">
                Try Alpha Generation
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </Card>

        {/* Back link */}
        <div className="mt-8">
          <Link
            href="/blog"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors inline-flex items-center gap-1"
          >
            ← Back to Blog
          </Link>
        </div>
      </div>
    </div>
  );
}
